oxidized_state_files() {
cat << EOF > 4ZF6_mcpbpy.frcmod
REMARK GOES HERE, THIS FILE IS GENERATED BY MCPB.PY
MASS
M1 55.85                              Fe ion
Y1 32.06         2.900               S in cystine
Y2 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y3 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y4 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y5 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
 
BOND
Y1-M1   74.9    2.3197      Created by Seminario method using MCPB.py
Y2-M1   52.1    2.0761      Created by Seminario method using MCPB.py
Y3-M1   42.2    2.1137      Created by Seminario method using MCPB.py
Y4-M1   42.3    2.1133      Created by Seminario method using MCPB.py
Y5-M1   53.4    2.0723      Created by Seminario method using MCPB.py
CT-Y1  237.0    1.810       changed from 222.0 based on methanethiol nmodes
cc-Y2  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y3  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y4  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y5  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cd-Y2  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y3  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y4  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y5  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
 
ANGL
CT-Y1-M1    62.03     106.09    Created by Seminario method using MCPB.py
Y1-M1-Y2    35.20     104.48    Created by Seminario method using MCPB.py
Y1-M1-Y3    36.64     100.33    Created by Seminario method using MCPB.py
Y1-M1-Y4    37.80     102.15    Created by Seminario method using MCPB.py
Y1-M1-Y5    33.52     106.70    Created by Seminario method using MCPB.py
Y2-M1-Y3    44.48      87.46    Created by Seminario method using MCPB.py
Y2-M1-Y4    43.43     153.31    Created by Seminario method using MCPB.py
Y2-M1-Y5    42.33      86.90    Created by Seminario method using MCPB.py
Y3-M1-Y4    46.27      86.03    Created by Seminario method using MCPB.py
Y3-M1-Y5    41.50     152.95    Created by Seminario method using MCPB.py
Y4-M1-Y5    43.71      87.24    Created by Seminario method using MCPB.py
cc-Y2-M1    64.80     127.11    Created by Seminario method using MCPB.py
cc-Y3-M1    81.21     124.83    Created by Seminario method using MCPB.py
cc-Y4-M1    67.10     126.47    Created by Seminario method using MCPB.py
cc-Y5-M1    77.47     126.28    Created by Seminario method using MCPB.py
cd-Y2-M1    80.38     125.81    Created by Seminario method using MCPB.py
cd-Y3-M1    65.56     127.28    Created by Seminario method using MCPB.py
cd-Y4-M1    78.87     125.05    Created by Seminario method using MCPB.py
cd-Y5-M1    66.90     127.26    Created by Seminario method using MCPB.py
CX-CT-Y1    50.0      108.60    AA cys (was CT-CT-SH)
Y1-CT-H1    50.0      109.50    AA cyx     changed based on NMA nmodes
Y2-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y3-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y4-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y5-cc-cc    71.6      112.56              SOURCE3          141    4.2871
cc-Y2-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y3-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y4-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y5-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cd-cd-Y2    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y3    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y4    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y5    67.6      121.98         CORR_SOURCE5          141    1.9633
ce-cc-Y2    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y3    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y4    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y5    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cd-Y2    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y3    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y4    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y5    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
 
DIHE
X -cc-Y2-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y3-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y4-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y5-X     2        9.5      180.0   2.0      statistic value from parm94
X -cd-Y2-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y3-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y4-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y5-X     2        9.5      180.0   2.0      statistiv value from parm94
CT-Y1-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CX-CT-Y1-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y1-CT-H1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y2-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y3-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y4-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y5-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y2-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y2-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y3-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y3-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y4-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y4-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y5-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y5-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y3-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y4-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y5-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y5-cd-ce-cc    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-Y2-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y2-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y2-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-ce-cd-Y2    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-ce-cd-Y3    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-ce-cd-Y4    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cd-Y2-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y2-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y2-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-ce-cc-Y2    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ce-cc-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ha-ce-cc-Y2    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y3    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y4    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y5    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cd-Y2    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y3    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y4    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y5    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
 
IMPR
Y3-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y4-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y2-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y4-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y5-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y2-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y5-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y3-cc-cc-ce         1.1          180.0         2.0          Using the default value
 
NONB
  M1          1.3860  0.0135709700       IOD set for Fe3+ ion in TIP3P water from Li et al. JPCB, 2015, 119, 883
  Y1          2.0000  0.2500             W. Cornell CH3SH and CH3SCH3 FEP's
  Y2          1.8240  0.1700             OPLS
  Y3          1.8240  0.1700             OPLS
  Y4          1.8240  0.1700             OPLS
  Y5          1.8240  0.1700             OPLS
 

EOF

cat << EOF > CM1.mol2
@<TRIPOS>MOLECULE
CM1
   10     9     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 N          -5.8430    0.8730   32.8250 N         1 CM1     -0.415700
      2 H          -5.8980    1.8700   32.9450 H         1 CM1      0.261734
      3 CA         -5.7470    0.3420   31.4690 CX        1 CM1     -0.035100
      4 HA         -6.6580   -0.2270   31.2760 H1        1 CM1      0.076209
      5 CB         -5.6920    1.4850   30.4520 CT        1 CM1     -0.080469
      6 HB2        -6.5540    2.1370   30.5980 H1        1 CM1      0.078893
      7 HB3        -4.7790    2.0500   30.6170 H1        1 CM1      0.078893
      8 SG         -5.6780    0.8990   28.7490 Y1        1 CM1     -0.421246
      9 C          -4.5470   -0.5790   31.2610 C         1 CM1      0.597300
     10 O          -3.4050   -0.1960   31.5100 O         1 CM1     -0.567900
@<TRIPOS>BOND
     1    1    2 1
     2    1    3 1
     3    3    4 1
     4    3    5 1
     5    3    9 1
     6    5    6 1
     7    5    7 1
     8    5    8 1
     9    9   10 1
@<TRIPOS>SUBSTRUCTURE
     1 CM1         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > FE1.mol2
@<TRIPOS>MOLECULE
FE1
    1     0     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 FE         -7.8900    0.8880   28.1050 M1        1 FE1      0.605857
@<TRIPOS>BOND
@<TRIPOS>SUBSTRUCTURE
     1 FE1         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > FMN-sq-H.frcmod
Remark line goes here
MASS

BOND

ANGLE

DIHE

IMPROPER
n -nc-c -o         10.5          180.0         2.0          Using general improper torsional angle  X- X- c- o, penalty score=  6.0)
c -c -n -hn         1.1          180.0         2.0          Using general improper torsional angle  X- X- n-hn, penalty score=  6.0)
cd-n -c -o         10.5          180.0         2.0          Using general improper torsional angle  X- X- c- o, penalty score=  6.0)
c -cd-cd-nc         1.1          180.0         2.0          Using the default value
ca-ca-ca-nc         1.1          180.0         2.0          Using the default value
ca-ca-ca-ha         1.1          180.0         2.0          Using general improper torsional angle  X- X-ca-ha, penalty score=  6.0)
ca-ca-ca-na         1.1          180.0         2.0          Using the default value
cd-na-cd-nc         1.1          180.0         2.0          Using the default value
c3-ca-na-cd         1.1          180.0         2.0          Using the default value

NONBON




EOF

cat << EOF > FMN-sq-H.mol2
@<TRIPOS>MOLECULE
FMN
   50    52     1     0     0
SMALL
resp


@<TRIPOS>ATOM
      1 P            6.0920    -0.1490    -0.7390 p5         1 FMN       1.380987
      2 O1P          7.0550    -0.7740    -1.6960 o          1 FMN      -0.931438
      3 O2P          6.1660    -0.6810     0.6960 o          1 FMN      -0.931438
      4 O3P          5.8950     1.3380    -0.8170 o          1 FMN      -0.931438
      5 C5'          3.4310    -0.4080    -0.5980 c3         1 FMN       0.192368
      6 O5'          4.5780    -0.8040    -1.2530 os         1 FMN      -0.608075
      7 C4'          3.0020    -1.4560     0.4390 c3         1 FMN       0.321223
      8 O4'          3.8960    -1.5150     1.5090 oh         1 FMN      -0.774819
      9 C3'          1.6330    -1.2170     1.1110 c3         1 FMN      -0.043461
     10 O3'          1.7410    -0.1100     1.9800 oh         1 FMN      -0.705790
     11 C2'          0.4270    -0.9700     0.1990 c3         1 FMN       0.315176
     12 O2'          0.3040    -1.9790    -0.7770 oh         1 FMN      -0.685688
     13 C1'         -0.8580    -0.9860     1.0370 c3         1 FMN      -0.024388
     14 N1          -3.1890    -2.3040     0.4620 nc         1 FMN      -0.769532
     15 C2          -4.2830    -3.0350     0.1840 c          1 FMN       0.999196
     16 O2          -4.4290    -4.2080     0.4720 o          1 FMN      -0.770756
     17 N3          -5.3270    -2.4010    -0.4740 n          1 FMN      -0.765878
     18 C4          -5.4010    -1.0710    -0.8380 c          1 FMN       0.719170
     19 C4A         -4.2200    -0.3280    -0.5000 cd         1 FMN      -0.026073
     20 O4          -6.4120    -0.6650    -1.3810 o          1 FMN      -0.708135
     21 C5A         -3.1230     1.6930    -0.3510 ca         1 FMN       0.616889
     22 N5          -4.1980     1.0150    -0.7780 nc         1 FMN      -0.646904
     23 C6          -3.1000     3.1010    -0.5260 ca         1 FMN      -0.495118
     24 C7          -2.0580     3.8960    -0.0690 ca         1 FMN       0.179084
     25 C7M         -2.0860     5.3910    -0.2900 c3         1 FMN      -0.253605
     26 C8          -0.9780     3.2750     0.6000 ca         1 FMN       0.068828
     27 C8M          0.1910     4.0800     1.1200 c3         1 FMN      -0.329318
     28 C9          -0.9790     1.8820     0.7750 ca         1 FMN      -0.325724
     29 C9A         -2.0140     1.0740     0.2960 ca         1 FMN      -0.205539
     30 C10         -3.1640    -1.0270     0.1250 cd         1 FMN       0.285107
     31 N10         -2.0140    -0.3230     0.4290 na         1 FMN       0.056950
     32 HO4'         4.8160    -1.2330     1.2060 ho         1 FMN       0.487624
     33 HO3'         2.6530    -0.1350     2.2630 ho         1 FMN       0.457467
     34 HO2'         1.0500    -1.9220    -1.3590 ho         1 FMN       0.401997
     35 HM83         0.6760     4.6440     0.3270 hc         1 FMN       0.095028
     36 HM82        -0.1170     4.7980     1.8800 hc         1 FMN       0.095028
     37 HM81         0.9400     3.4320     1.5570 hc         1 FMN       0.095028
     38 HM73        -1.2420     5.7270    -0.8880 hc         1 FMN       0.056257
     39 HM72        -2.9940     5.6870    -0.8060 hc         1 FMN       0.056257
     40 HM71        -2.0460     5.9410     0.6490 hc         1 FMN       0.056257
     41 H5'2         2.6310    -0.2950    -1.3410 h1         1 FMN       0.009931
     42 H5'1         3.5520     0.5600    -0.1210 h1         1 FMN       0.009931
     43 H1'2        -0.6620    -0.5260     1.9970 h1         1 FMN       0.065041
     44 H1'1        -1.1360    -2.0110     1.2020 h1         1 FMN       0.065041
     45 HN3         -6.1260    -2.9590    -0.6730 hn         1 FMN       0.348135
     46 H9          -0.1380     1.4440     1.2740 ha         1 FMN       0.238862
     47 H6          -3.9470     3.5330    -1.0290 ha         1 FMN       0.178514
     48 H4'          2.9620    -2.4190    -0.0740 h1         1 FMN      -0.025770
     49 H3'          1.4260    -2.1110     1.7010 h1         1 FMN       0.086943
     50 H2'          0.5520    -0.0110    -0.2860 h1         1 FMN       0.020570
@<TRIPOS>BOND
     1     1     2 1   
     2     1     3 1   
     3     1     4 1   
     4     1     6 1   
     5     5     6 1   
     6     5     7 1   
     7     5    41 1   
     8     5    42 1   
     9     7     8 1   
    10     7     9 1   
    11     7    48 1   
    12     8    32 1   
    13     9    10 1   
    14     9    11 1   
    15     9    49 1   
    16    10    33 1   
    17    11    12 1   
    18    11    13 1   
    19    11    50 1   
    20    12    34 1   
    21    13    31 1   
    22    13    43 1   
    23    13    44 1   
    24    14    15 1   
    25    14    30 2   
    26    15    16 2   
    27    15    17 1   
    28    17    18 1   
    29    17    45 1   
    30    18    19 1   
    31    18    20 2   
    32    19    22 2   
    33    19    30 1   
    34    21    22 1   
    35    21    23 ar  
    36    21    29 ar  
    37    23    24 ar  
    38    23    47 1   
    39    24    25 1   
    40    24    26 ar  
    41    25    38 1   
    42    25    39 1   
    43    25    40 1   
    44    26    27 1   
    45    26    28 ar  
    46    27    35 1   
    47    27    36 1   
    48    27    37 1   
    49    28    29 ar  
    50    28    46 1   
    51    29    31 1   
    52    30    31 1   
@<TRIPOS>SUBSTRUCTURE
     1 FMN         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > HEM.frcmod
Remark line goes here
MASS

BOND

ANGLE

DIHE
cd-cd-ce-cc   4   26.600       180.000           2.000      same as X -ce-cf-X , penalty score=136.0
nd-cd-ce-cc   4   26.600       180.000           2.000      same as X -ce-cf-X , penalty score=136.0
cc-cc-ce-cd   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cc-cc-ce-ha   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cd-cd-ce-ha   4   16.000       180.000           2.000      same as X -cc-cd-X , penalty score=136.0
nd-cc-ce-cd   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cc-cd-cf-c2   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cc-cd-cf-ha   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cd-cd-cf-c2   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cd-cd-cf-ha   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
nd-cc-ce-ha   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
nd-cd-ce-ha   4   16.000       180.000           2.000      same as X -cc-cd-X , penalty score=136.0

IMPROPER
cc-cd-ce-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 46.8 (use general term))
cc-ce-cc-nd         1.1          180.0         2.0          Using the default value
c3-cc-cc-cd         1.1          180.0         2.0          Using the default value
c3-cc-cd-cd         1.1          180.0         2.0          Using the default value
cd-ce-cd-nd         1.1          180.0         2.0          Using the default value
c3-o -c -o          1.1          180.0         2.0          Using general improper torsional angle  X- o- c- o, penalty score=  3.0)
cc-cd-cd-cf         1.1          180.0         2.0          Same as c2-ca-ca-ca, penalty score=304.0)
c2-cd-cf-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 46.8 (use general term))
cf-ha-c2-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 47.1 (use general term))

NONBON




EOF

cat << EOF > HM1.mol2
@<TRIPOS>MOLECULE
HM1
   72    76     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 CHA        -9.0610   -0.2850   31.0490 ce        1 HM1     -0.020977
      2 CHB        -8.7960    4.1460   29.0620 ce        1 HM1     -0.174040
      3 CHC        -6.5140    2.2100   25.2690 ce        1 HM1     -0.134929
      4 CHD        -7.5560   -2.2780   26.8190 ce        1 HM1     -0.063142
      5 C1A        -9.1600    1.0750   30.8620 cc        1 HM1     -0.067280
      6 C2A        -9.7050    2.0250   31.8140 cc        1 HM1     -0.070442
      7 C3A        -9.6310    3.2440   31.2680 cd        1 HM1      0.077300
      8 C4A        -9.0360    3.1170   29.9500 cd        1 HM1     -0.077985
      9 CMA       -10.1010    4.5580   31.9240 c3        1 HM1     -0.114741
     10 CAA       -10.2720    1.6890   33.2100 c3        1 HM1     -0.023009
     11 CBA       -11.7690    1.4250   33.1010 c3        1 HM1     -0.024939
     12 CGA       -12.4320    1.4980   34.4530 c         1 HM1      0.649658
     13 O1A       -13.6650    1.2580   34.5320 o         1 HM1     -0.663208
     14 O2A       -11.7340    1.7980   35.4550 o         1 HM1     -0.652195
     15 C1B        -8.1270    4.0160   27.8650 cc        1 HM1     -0.043676
     16 C2B        -7.7320    5.0950   26.9750 cc        1 HM1      0.064549
     17 C3B        -7.1090    4.5430   25.9200 cd        1 HM1     -0.044451
     18 C4B        -7.0750    3.1140   26.1310 cd        1 HM1     -0.028481
     19 CMB        -8.0270    6.5900   27.2360 c3        1 HM1     -0.065755
     20 CAB        -6.4620    5.2020   24.6780 cf        1 HM1     -0.102547
     21 CBB        -6.1120    6.4900   24.6060 c2        1 HM1     -0.380971
     22 C1C        -6.5780    0.8430   25.3700 cc        1 HM1      0.001834
     23 C2C        -5.9460   -0.0720   24.4550 cc        1 HM1      0.059292
     24 C3C        -6.2070   -1.3100   24.8560 cd        1 HM1      0.004209
     25 C4C        -7.0350   -1.2400   26.0600 cd        1 HM1      0.021100
     26 CMC        -5.1000    0.3080   23.2200 c3        1 HM1     -0.101973
     27 CAC        -5.6640   -2.5280   24.0850 cf        1 HM1     -0.150879
     28 CBC        -5.8300   -3.7640   24.5300 c2        1 HM1     -0.414384
     29 C1D        -8.0580   -2.1880   28.1080 cc        1 HM1     -0.043867
     30 C2D        -8.4720   -3.2930   28.9590 cc        1 HM1      0.016531
     31 C3D        -8.9400   -2.6480   30.2710 cd        1 HM1     -0.118024
     32 C4D        -8.7620   -1.2300   30.0910 cd        1 HM1     -0.031337
     33 CMD        -8.4690   -4.8040   28.6400 c3        1 HM1     -0.021954
     34 CAD        -9.4730   -3.3430   31.5400 c3        1 HM1     -0.024418
     35 CBD        -8.2700   -3.8530   32.3340 c3        1 HM1     -0.007141
     36 CGD        -8.6830   -4.2760   33.7200 c         1 HM1      0.566730
     37 O1D        -8.2760   -5.3860   34.1590 o         1 HM1     -0.615339
     38 O2D        -9.4290   -3.5060   34.3790 o         1 HM1     -0.594830
     39 NA         -8.7590    1.7760   29.7370 Y2        1 HM1     -0.111040
     40 NB         -7.7070    2.8170   27.3180 Y3        1 HM1     -0.160766
     41 NC         -7.2360    0.1030   26.3370 Y4        1 HM1     -0.260020
     42 ND         -8.2480   -1.0010   28.8150 Y5        1 HM1     -0.209730
     43 HMA1      -10.8410    4.3740   32.5230 hc        1 HM1      0.036565
     44 HMA2      -10.3890    5.1780   31.2360 hc        1 HM1      0.036565
     45 HMA3       -9.3690    4.9490   32.4260 hc        1 HM1      0.036565
     46 HMB1       -8.8490    6.6740   27.7450 hc        1 HM1      0.024199
     47 HMB2       -8.1220    7.0540   26.3890 hc        1 HM1      0.024199
     48 HMB3       -7.2950    6.9820   27.7380 hc        1 HM1      0.024199
     49 HMC1       -4.4330   -0.3780   23.0610 hc        1 HM1      0.029246
     50 HMC2       -4.6580    1.1570   23.3790 hc        1 HM1      0.029246
     51 HMC3       -5.6770    0.3840   22.4440 hc        1 HM1      0.029246
     52 HMD1       -8.3320   -5.3070   29.4580 hc        1 HM1      0.019201
     53 HMD2       -7.7540   -5.0020   28.0150 hc        1 HM1      0.019201
     54 HMD3       -9.3200   -5.0530   28.2460 hc        1 HM1      0.019201
     55 HBB1       -5.7100    6.8390   23.7950 ha        1 HM1      0.141609
     56 HBB2       -6.2600    7.0760   25.3650 ha        1 HM1      0.141609
     57 HBC1       -5.4780   -4.5130   24.0240 ha        1 HM1      0.165217
     58 HBC2       -6.3040   -3.9200   25.3620 ha        1 HM1      0.165217
     59 HBA1      -11.9190    0.5500   32.7110 hc        1 HM1      0.001039
     60 HBA2      -12.1720    2.0740   32.5040 hc        1 HM1      0.001039
     61 HAA1      -10.1070    2.4230   33.8220 hc        1 HM1      0.041528
     62 HAA2       -9.8220    0.9100   33.5730 hc        1 HM1      0.041528
     63 HBD1       -7.5960   -3.1570   32.3910 hc        1 HM1      0.012159
     64 HBD2       -7.8650   -4.6020   31.8700 hc        1 HM1      0.012159
     65 HAD1      -10.0610   -4.0780   31.3040 hc        1 HM1      0.040801
     66 HAD2       -9.9940   -2.7230   32.0740 hc        1 HM1      0.040801
     67 HHA        -9.2110   -0.5990   31.9110 ha        1 HM1      0.171463
     68 HHB        -9.1100    4.9910   29.2890 ha        1 HM1      0.171231
     69 HHC        -6.0440    2.5560   24.5450 ha        1 HM1      0.135626
     70 HHD        -7.5700   -3.1190   26.4230 ha        1 HM1      0.081355
     71 HAB        -6.3000    4.6440   23.9010 ha        1 HM1      0.128211
     72 HAC        -5.1880   -2.3860   23.2520 ha        1 HM1      0.158570
@<TRIPOS>BOND
     1    1    5 1
     2    1   32 1
     3    1   67 1
     4    2    8 1
     5    2   15 1
     6    2   68 1
     7    3   18 1
     8    3   22 1
     9    3   69 1
    10    4   25 1
    11    4   29 1
    12    4   70 1
    13    5    6 1
    14    5   39 1
    15    6    7 1
    16    6   10 1
    17    7    8 1
    18    7    9 1
    19    8   39 1
    20    9   43 1
    21    9   44 1
    22    9   45 1
    23   10   11 1
    24   10   61 1
    25   10   62 1
    26   11   12 1
    27   11   59 1
    28   11   60 1
    29   12   13 1
    30   12   14 1
    31   15   16 1
    32   15   40 1
    33   16   17 1
    34   16   19 1
    35   17   18 1
    36   17   20 1
    37   18   40 1
    38   19   46 1
    39   19   47 1
    40   19   48 1
    41   20   21 1
    42   20   71 1
    43   21   55 1
    44   21   56 1
    45   22   23 1
    46   22   41 1
    47   23   24 1
    48   23   26 1
    49   24   25 1
    50   24   27 1
    51   25   41 1
    52   26   49 1
    53   26   50 1
    54   26   51 1
    55   27   28 1
    56   27   72 1
    57   28   57 1
    58   28   58 1
    59   29   30 1
    60   29   42 1
    61   30   31 1
    62   30   33 1
    63   31   32 1
    64   31   34 1
    65   32   42 1
    66   33   52 1
    67   33   53 1
    68   33   54 1
    69   34   35 1
    70   34   65 1
    71   34   66 1
    72   35   36 1
    73   35   63 1
    74   35   64 1
    75   36   37 1
    76   36   38 1
@<TRIPOS>SUBSTRUCTURE
     1 HM1         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > tleap.in
source leaprc.protein.ff19SB
source leaprc.gaff2
source leaprc.water.tip3p
addAtomTypes {
        { "M1"  "Fe" "sp3" }
        { "Y1"  "S" "sp3" }
        { "Y2"  "N" "sp3" }
        { "Y3"  "N" "sp3" }
        { "Y4"  "N" "sp3" }
        { "Y5"  "N" "sp3" }
}
CM1 = loadmol2 CM1.mol2
HM1 = loadmol2 HM1.mol2
FE1 = loadmol2 FE1.mol2
FMN = loadmol2 FMN-sq-H.mol2
LIG = loadmol2 $ligand.mol2 
loadamberparams $ligand.frcmod
loadamberparams HEM.frcmod
loadamberparams frcmod.ions1lm_126_tip3p
loadamberparams 4ZF6_mcpbpy.frcmod
loadamberparams FMN-sq-H.frcmod
mol = loadpdb protein.pdb
bond mol.381.SG mol.613.FE
bond mol.612.NA mol.613.FE
bond mol.612.NB mol.613.FE
bond mol.612.NC mol.613.FE
bond mol.612.ND mol.613.FE
bond mol.380.C mol.381.N
bond mol.381.C mol.382.N
savepdb mol protein_dry.pdb
saveamberparm mol protein_dry.prmtop protein_dry.inpcrd
charge mol
solvatebox mol TIP3PBOX 10.0
addions mol K+ 0
addions mol Cl- 0
charge mol
check mol
savepdb mol protein_solv.pdb
saveamberparm mol protein_solv.prmtop protein_solv.inpcrd
quit
EOF
}
reduced_state_files() {
cat << EOF > 4ZF6_mcpbpy.frcmod
REMARK GOES HERE, THIS FILE IS GENERATED BY MCPB.PY
MASS
M1 55.85                              Fe ion
Y1 32.06         2.900               S in cystine
Y2 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y3 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y4 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
Y5 14.01         0.530               Sp2 N in non-pure aromatic systems, identical to nc
 
BOND
Y1-M1   56.3    2.4288      Created by Seminario method using MCPB.py
Y2-M1   39.1    2.1205      Created by Seminario method using MCPB.py
Y3-M1   35.1    2.1684      Created by Seminario method using MCPB.py
Y4-M1   34.9    2.1651      Created by Seminario method using MCPB.py
Y5-M1   39.4    2.1223      Created by Seminario method using MCPB.py
CT-Y1  237.0    1.810       changed from 222.0 based on methanethiol nmodes
cc-Y2  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y3  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y4  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cc-Y5  525.4    1.3172      SOURCE3_SOURCE5    4612	 0.0083
cd-Y2  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y3  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y4  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
cd-Y5  441.1    1.3694      SOURCE1_SOURCE5    2269	 0.0086
 
ANGL
CT-Y1-M1    91.60     104.85    Created by Seminario method using MCPB.py
Y1-M1-Y2    37.78     107.29    Created by Seminario method using MCPB.py
Y1-M1-Y3    34.19     101.75    Created by Seminario method using MCPB.py
Y1-M1-Y4    29.50     103.67    Created by Seminario method using MCPB.py
Y1-M1-Y5    46.33     109.38    Created by Seminario method using MCPB.py
Y2-M1-Y3    38.91      86.51    Created by Seminario method using MCPB.py
Y2-M1-Y4    31.85     148.90    Created by Seminario method using MCPB.py
Y2-M1-Y5    40.15      86.38    Created by Seminario method using MCPB.py
Y3-M1-Y4    49.02      84.45    Created by Seminario method using MCPB.py
Y3-M1-Y5    35.13     148.80    Created by Seminario method using MCPB.py
Y4-M1-Y5    41.76      86.13    Created by Seminario method using MCPB.py
cc-Y2-M1    73.57     126.56    Created by Seminario method using MCPB.py
cc-Y3-M1    77.40     124.12    Created by Seminario method using MCPB.py
cc-Y4-M1    67.53     125.96    Created by Seminario method using MCPB.py
cc-Y5-M1    87.36     126.53    Created by Seminario method using MCPB.py
cd-Y2-M1    66.29     125.90    Created by Seminario method using MCPB.py
cd-Y3-M1    75.19     127.15    Created by Seminario method using MCPB.py
cd-Y4-M1    64.83     124.40    Created by Seminario method using MCPB.py
cd-Y5-M1    84.07     126.63    Created by Seminario method using MCPB.py
CX-CT-Y1    50.0      108.60    AA cys (was CT-CT-SH)
Y1-CT-H1    50.0      109.50    AA cyx     changed based on NMA nmodes
Y2-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y3-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y4-cc-cc    71.6      112.56              SOURCE3          141    4.2871
Y5-cc-cc    71.6      112.56              SOURCE3          141    4.2871
cc-Y2-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y3-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y4-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cc-Y5-cd    71.8      105.49         CORR_SOURCE5         1810    1.9032
cd-cd-Y2    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y3    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y4    67.6      121.98         CORR_SOURCE5          141    1.9633
cd-cd-Y5    67.6      121.98         CORR_SOURCE5          141    1.9633
ce-cc-Y2    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y3    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y4    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cc-Y5    68.1      121.70         CORR_SOURCE5           58    1.4179
ce-cd-Y2    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y3    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y4    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
ce-cd-Y5    68.7      123.98      SOURCE4_SOURCE5           10    2.4097
 
DIHE
X -cc-Y2-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y3-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y4-X     2        9.5      180.0   2.0      statistic value from parm94
X -cc-Y5-X     2        9.5      180.0   2.0      statistic value from parm94
X -cd-Y2-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y3-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y4-X     2        9.5      180.0   2.0      statistiv value from parm94
X -cd-Y5-X     2        9.5      180.0   2.0      statistiv value from parm94
CT-Y1-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CT-Y1-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
CX-CT-Y1-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y1-CT-H1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y2-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y3-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y4-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
M1-Y5-cc-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y2-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y2-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y3-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y3-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y4-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y4-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y5-cc    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y1-M1-Y5-cd    3       0.00       0.00   3.0    Treat as zero by MCPB.py
Y3-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y4-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y5-cc-ce-cd    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
Y5-cd-ce-cc    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-Y2-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y2-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y2-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y3-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y4-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-Y5-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cc-ce-cd-Y2    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-ce-cd-Y3    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cc-ce-cd-Y4    4       26.6      180.0   2.0      same as X -ce-cf-X , penalty score=136.0
cd-Y2-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y2-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y2-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y3-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y4-M1-Y5    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y2    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y3    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-Y5-M1-Y4    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-cd-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
cd-ce-cc-Y2    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ce-cc-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cc-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y2-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y3-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y4-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ce-cd-Y5-M1    3       0.00       0.00   3.0    Treat as zero by MCPB.py
ha-ce-cc-Y2    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y3    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y4    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cc-Y5    4        4.0      180.0   2.0      same as X -ce-ce-X , penalty score=136.0
ha-ce-cd-Y2    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y3    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y4    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
ha-ce-cd-Y5    4       16.0      180.0   2.0      same as X -cc-cd-X , penalty score=136.0
 
IMPR
Y3-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y4-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y2-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y4-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y5-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y2-cc-cc-ce         1.1          180.0         2.0          Using the default value
Y5-cd-cd-ce         1.1          180.0         2.0          Using the default value
Y3-cc-cc-ce         1.1          180.0         2.0          Using the default value
 
NONB
  M1          1.4090  0.0172100000       IOD set for Fe2+ ion from Li et al. JCTC, 2013, 9, 2733
  Y1          2.0000  0.2500             W. Cornell CH3SH and CH3SCH3 FEP's
  Y2          1.8240  0.1700             OPLS
  Y3          1.8240  0.1700             OPLS
  Y4          1.8240  0.1700             OPLS
  Y5          1.8240  0.1700             OPLS
 

EOF
cat << EOF > CM1.mol2
@<TRIPOS>MOLECULE
CM1
   10     9     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 N          -5.8430    0.8730   32.8250 N         1 CM1     -0.415700
      2 H          -5.8980    1.8700   32.9450 H         1 CM1      0.250336
      3 CA         -5.7470    0.3420   31.4690 CX        1 CM1     -0.035100
      4 HA         -6.6580   -0.2270   31.2760 H1        1 CM1      0.061438
      5 CB         -5.6920    1.4850   30.4520 CT        1 CM1     -0.207370
      6 HB2        -6.5540    2.1370   30.5980 H1        1 CM1      0.113926
      7 HB3        -4.7790    2.0500   30.6170 H1        1 CM1      0.113926
      8 SG         -5.6780    0.8990   28.7490 Y1        1 CM1     -0.495785
      9 C          -4.5470   -0.5790   31.2610 C         1 CM1      0.597300
     10 O          -3.4050   -0.1960   31.5100 O         1 CM1     -0.567900
@<TRIPOS>BOND
     1    1    2 1
     2    1    3 1
     3    3    4 1
     4    3    5 1
     5    3    9 1
     6    5    6 1
     7    5    7 1
     8    5    8 1
     9    9   10 1
@<TRIPOS>SUBSTRUCTURE
     1 CM1         1 TEMP              0 ****  ****    0 ROOT
EOF

cat << EOF > FE1.mol2
@<TRIPOS>MOLECULE
FE1
    1     0     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 FE         -7.8900    0.8880   28.1050 M1        1 FE1      0.789001
@<TRIPOS>BOND
@<TRIPOS>SUBSTRUCTURE
     1 FE1         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > FMN-ox-H.frcmod
Remark line goes here
MASS

BOND

ANGLE

DIHE

IMPROPER
n -nc-c -o         10.5          180.0         2.0          Using general improper torsional angle  X- X- c- o, penalty score=  6.0)
c -c -n -hn         1.1          180.0         2.0          Using general improper torsional angle  X- X- n-hn, penalty score=  6.0)
cd-n -c -o         10.5          180.0         2.0          Using general improper torsional angle  X- X- c- o, penalty score=  6.0)
c -cd-cd-nc         1.1          180.0         2.0          Using the default value
ca-ca-ca-nc         1.1          180.0         2.0          Using the default value
ca-ca-ca-ha         1.1          180.0         2.0          Using general improper torsional angle  X- X-ca-ha, penalty score=  6.0)
ca-ca-ca-na         1.1          180.0         2.0          Using the default value
cd-na-cd-nc         1.1          180.0         2.0          Using the default value
c3-ca-na-cd         1.1          180.0         2.0          Using the default value

NONBON


EOF

cat << EOF > FMN-ox-H.mol2
@<TRIPOS>MOLECULE
FMN
   50    52     1     0     0
SMALL
resp


@<TRIPOS>ATOM
      1 P            4.2280     0.4090     0.2020 p5         1 FMN       1.336589
      2 O1P          5.3140     1.4180     0.1510 o          1 FMN      -0.881481
      3 O2P          4.3900    -0.7160     1.2270 o          1 FMN      -0.881481
      4 O3P          2.8010     0.9310     0.1780 o          1 FMN      -0.881481
      5 C5'          3.3600    -1.2530    -1.7240 c3         1 FMN       0.149784
      6 O5'          4.3630    -0.4390    -1.2500 os         1 FMN      -0.554281
      7 C4'          2.9090    -2.4480    -0.8390 c3         1 FMN       0.424508
      8 O4'          4.0160    -3.0530    -0.2480 oh         1 FMN      -0.734070
      9 C3'          1.7490    -2.2840     0.2000 c3         1 FMN       0.009741
     10 O3'          2.1420    -1.9770     1.4940 oh         1 FMN      -0.685222
     11 C2'          0.6540    -1.3080    -0.2680 c3         1 FMN       0.262941
     12 O2'         -0.0580    -1.8200    -1.3870 oh         1 FMN      -0.686132
     13 C1'         -0.3440    -1.0940     0.8650 c3         1 FMN       0.010293
     14 N1          -2.8990    -2.0530     0.5640 nc         1 FMN      -0.754087
     15 C2          -4.1180    -2.6170     0.3950 c          1 FMN       0.990130
     16 O2          -4.3820    -3.7630     0.6320 o          1 FMN      -0.680778
     17 N3          -5.1650    -1.8130    -0.0910 n          1 FMN      -0.760751
     18 C4          -5.1230    -0.4840    -0.3690 c          1 FMN       0.700736
     19 C4A         -3.7780     0.1070    -0.1320 cd         1 FMN       0.252482
     20 O4          -6.0800     0.1250    -0.7550 o          1 FMN      -0.617535
     21 C5A         -2.4080     1.9110    -0.0880 ca         1 FMN       0.499270
     22 N5          -3.6290     1.3610    -0.3040 nc         1 FMN      -0.581627
     23 C6          -2.2640     3.3000    -0.2570 ca         1 FMN      -0.456451
     24 C7          -1.0640     3.9180    -0.0730 ca         1 FMN       0.137182
     25 C7M         -0.9300     5.4110    -0.2600 c3         1 FMN      -0.309099
     26 C8           0.0600     3.1210     0.2850 ca         1 FMN       0.144036
     27 C8M          1.4250     3.7420     0.4670 c3         1 FMN      -0.201962
     28 C9          -0.0680     1.7620     0.4680 ca         1 FMN      -0.326148
     29 C9A         -1.3090     1.1290     0.2870 ca         1 FMN      -0.098926
     30 C10         -2.7100    -0.7920     0.3050 cd         1 FMN       0.360499
     31 N10         -1.4930    -0.2340     0.4680 na         1 FMN      -0.008155
     32 H04'         4.4110    -2.3730     0.3130 ho         1 FMN       0.448069
     33 H03'         2.9480    -1.4140     1.4890 ho         1 FMN       0.440993
     34 HO2'         0.4470    -1.6250    -2.1630 ho         1 FMN       0.367069
     35 HM83         2.1860     2.9710     0.5040 hc         1 FMN       0.075852
     36 HM82         1.6550     4.4170    -0.3530 hc         1 FMN       0.075852
     37 HM81         1.4530     4.3330     1.3830 hc         1 FMN       0.075852
     38 HM73        -1.8960     5.8590    -0.4700 hc         1 FMN       0.078962
     39 HM72        -0.5250     5.8900     0.6270 hc         1 FMN       0.078962
     40 HM71        -0.2640     5.6530    -1.0830 hc         1 FMN       0.078962
     41 H5'2         3.7550    -1.7140    -2.6300 h1         1 FMN      -0.021614
     42 H5'1         2.4940    -0.6650    -2.0310 h1         1 FMN      -0.021614
     43 H1'2         0.1540    -0.6270     1.6960 h1         1 FMN       0.076716
     44 H1'1        -0.7620    -2.0290     1.1850 h1         1 FMN       0.076716
     45 HN3         -6.0390    -2.2760    -0.2130 hn         1 FMN       0.370741
     46 H9           0.8300     1.2180     0.6950 ha         1 FMN       0.281214
     47 H6          -3.1450     3.8490    -0.5380 ha         1 FMN       0.205760
     48 H4'          2.5150    -3.1690    -1.5560 h1         1 FMN      -0.066585
     49 H3'          1.2750    -3.2640     0.2510 h1         1 FMN       0.071041
     50 H2'          1.1140    -0.3690    -0.5190 h1         1 FMN       0.128527
@<TRIPOS>BOND
     1     1     2 1   
     2     1     3 1   
     3     1     4 1   
     4     1     6 1   
     5     5     6 1   
     6     5     7 1   
     7     5    41 1   
     8     5    42 1   
     9     7     8 1   
    10     7     9 1   
    11     7    48 1   
    12     8    32 1   
    13     9    10 1   
    14     9    11 1   
    15     9    49 1   
    16    10    33 1   
    17    11    12 1   
    18    11    13 1   
    19    11    50 1   
    20    12    34 1   
    21    13    31 1   
    22    13    43 1   
    23    13    44 1   
    24    14    15 1   
    25    14    30 2   
    26    15    16 2   
    27    15    17 1   
    28    17    18 1   
    29    17    45 1   
    30    18    19 1   
    31    18    20 2   
    32    19    22 2   
    33    19    30 1   
    34    21    22 1   
    35    21    23 ar  
    36    21    29 ar  
    37    23    24 ar  
    38    23    47 1   
    39    24    25 1   
    40    24    26 ar  
    41    25    38 1   
    42    25    39 1   
    43    25    40 1   
    44    26    27 1   
    45    26    28 ar  
    46    27    35 1   
    47    27    36 1   
    48    27    37 1   
    49    28    29 ar  
    50    28    46 1   
    51    29    31 1   
    52    30    31 1   
@<TRIPOS>SUBSTRUCTURE
     1 FMN         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > HEM.frcmod
Remark line goes here
MASS

BOND

ANGLE

DIHE
cd-cd-ce-cc   4   26.600       180.000           2.000      same as X -ce-cf-X , penalty score=136.0
nd-cd-ce-cc   4   26.600       180.000           2.000      same as X -ce-cf-X , penalty score=136.0
cc-cc-ce-cd   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cc-cc-ce-ha   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cd-cd-ce-ha   4   16.000       180.000           2.000      same as X -cc-cd-X , penalty score=136.0
nd-cc-ce-cd   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
cc-cd-cf-c2   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cc-cd-cf-ha   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cd-cd-cf-c2   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
cd-cd-cf-ha   4    4.000       180.000           2.000      same as X -cf-cf-X , penalty score=136.0
nd-cc-ce-ha   4    4.000       180.000           2.000      same as X -ce-ce-X , penalty score=136.0
nd-cd-ce-ha   4   16.000       180.000           2.000      same as X -cc-cd-X , penalty score=136.0

IMPROPER
cc-cd-ce-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 46.8 (use general term))
cc-ce-cc-nd         1.1          180.0         2.0          Using the default value
c3-cc-cc-cd         1.1          180.0         2.0          Using the default value
c3-cc-cd-cd         1.1          180.0         2.0          Using the default value
cd-ce-cd-nd         1.1          180.0         2.0          Using the default value
c3-o -c -o          1.1          180.0         2.0          Using general improper torsional angle  X- o- c- o, penalty score=  3.0)
cc-cd-cd-cf         1.1          180.0         2.0          Same as c2-ca-ca-ca, penalty score=304.0)
c2-cd-cf-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 46.8 (use general term))
cf-ha-c2-ha         1.1          180.0         2.0          Same as X -X -ca-ha, penalty score= 47.1 (use general term))

NONBON




EOF

cat << EOF > HM1.mol2
@<TRIPOS>MOLECULE
HM1
   72    76     1     0     0
SMALL
RESP Charge
 
 
@<TRIPOS>ATOM
      1 CHA        -9.0610   -0.2850   31.0490 ce        1 HM1     -0.039060
      2 CHB        -8.7960    4.1460   29.0620 ce        1 HM1     -0.243713
      3 CHC        -6.5140    2.2100   25.2690 ce        1 HM1     -0.303960
      4 CHD        -7.5560   -2.2780   26.8190 ce        1 HM1     -0.172728
      5 C1A        -9.1600    1.0750   30.8620 cc        1 HM1      0.002879
      6 C2A        -9.7050    2.0250   31.8140 cc        1 HM1     -0.165086
      7 C3A        -9.6310    3.2440   31.2680 cd        1 HM1      0.176549
      8 C4A        -9.0360    3.1170   29.9500 cd        1 HM1     -0.031820
      9 CMA       -10.1010    4.5580   31.9240 c3        1 HM1     -0.294917
     10 CAA       -10.2720    1.6890   33.2100 c3        1 HM1      0.086453
     11 CBA       -11.7690    1.4250   33.1010 c3        1 HM1     -0.153318
     12 CGA       -12.4320    1.4980   34.4530 c         1 HM1      0.726821
     13 O1A       -13.6650    1.2580   34.5320 o         1 HM1     -0.780854
     14 O2A       -11.7340    1.7980   35.4550 o         1 HM1     -0.743131
     15 C1B        -8.1270    4.0160   27.8650 cc        1 HM1      0.013898
     16 C2B        -7.7320    5.0950   26.9750 cc        1 HM1      0.142628
     17 C3B        -7.1090    4.5430   25.9200 cd        1 HM1     -0.165113
     18 C4B        -7.0750    3.1140   26.1310 cd        1 HM1      0.102141
     19 CMB        -8.0270    6.5900   27.2360 c3        1 HM1     -0.227604
     20 CAB        -6.4620    5.2020   24.6780 cf        1 HM1     -0.008465
     21 CBB        -6.1120    6.4900   24.6060 c2        1 HM1     -0.513784
     22 C1C        -6.5780    0.8430   25.3700 cc        1 HM1      0.129687
     23 C2C        -5.9460   -0.0720   24.4550 cc        1 HM1      0.130112
     24 C3C        -6.2070   -1.3100   24.8560 cd        1 HM1     -0.124797
     25 C4C        -7.0350   -1.2400   26.0600 cd        1 HM1      0.211875
     26 CMC        -5.1000    0.3080   23.2200 c3        1 HM1     -0.251805
     27 CAC        -5.6640   -2.5280   24.0850 cf        1 HM1     -0.067524
     28 CBC        -5.8300   -3.7640   24.5300 c2        1 HM1     -0.497586
     29 C1D        -8.0580   -2.1880   28.1080 cc        1 HM1      0.029620
     30 C2D        -8.4720   -3.2930   28.9590 cc        1 HM1      0.076098
     31 C3D        -8.9400   -2.6480   30.2710 cd        1 HM1     -0.227402
     32 C4D        -8.7620   -1.2300   30.0910 cd        1 HM1      0.077078
     33 CMD        -8.4690   -4.8040   28.6400 c3        1 HM1     -0.084425
     34 CAD        -9.4730   -3.3430   31.5400 c3        1 HM1      0.030762
     35 CBD        -8.2700   -3.8530   32.3340 c3        1 HM1     -0.139880
     36 CGD        -8.6830   -4.2760   33.7200 c         1 HM1      0.652093
     37 O1D        -8.2760   -5.3860   34.1590 o         1 HM1     -0.753853
     38 O2D        -9.4290   -3.5060   34.3790 o         1 HM1     -0.694374
     39 NA         -8.7590    1.7760   29.7370 Y2        1 HM1     -0.265232
     40 NB         -7.7070    2.8170   27.3180 Y3        1 HM1     -0.277413
     41 NC         -7.2360    0.1030   26.3370 Y4        1 HM1     -0.504390
     42 ND         -8.2480   -1.0010   28.8150 Y5        1 HM1     -0.369059
     43 HMA1      -10.8410    4.3740   32.5230 hc        1 HM1      0.069498
     44 HMA2      -10.3890    5.1780   31.2360 hc        1 HM1      0.069498
     45 HMA3       -9.3690    4.9490   32.4260 hc        1 HM1      0.069498
     46 HMB1       -8.8490    6.6740   27.7450 hc        1 HM1      0.055180
     47 HMB2       -8.1220    7.0540   26.3890 hc        1 HM1      0.055180
     48 HMB3       -7.2950    6.9820   27.7380 hc        1 HM1      0.055180
     49 HMC1       -4.4330   -0.3780   23.0610 hc        1 HM1      0.055375
     50 HMC2       -4.6580    1.1570   23.3790 hc        1 HM1      0.055375
     51 HMC3       -5.6770    0.3840   22.4440 hc        1 HM1      0.055375
     52 HMD1       -8.3320   -5.3070   29.4580 hc        1 HM1      0.022858
     53 HMD2       -7.7540   -5.0020   28.0150 hc        1 HM1      0.022858
     54 HMD3       -9.3200   -5.0530   28.2460 hc        1 HM1      0.022858
     55 HBB1       -5.7100    6.8390   23.7950 ha        1 HM1      0.162723
     56 HBB2       -6.2600    7.0760   25.3650 ha        1 HM1      0.162723
     57 HBC1       -5.4780   -4.5130   24.0240 ha        1 HM1      0.174261
     58 HBC2       -6.3040   -3.9200   25.3620 ha        1 HM1      0.174261
     59 HBA1      -11.9190    0.5500   32.7110 hc        1 HM1      0.018163
     60 HBA2      -12.1720    2.0740   32.5040 hc        1 HM1      0.018163
     61 HAA1      -10.1070    2.4230   33.8220 hc        1 HM1      0.021655
     62 HAA2       -9.8220    0.9100   33.5730 hc        1 HM1      0.021655
     63 HBD1       -7.5960   -3.1570   32.3910 hc        1 HM1      0.036295
     64 HBD2       -7.8650   -4.6020   31.8700 hc        1 HM1      0.036295
     65 HAD1      -10.0610   -4.0780   31.3040 hc        1 HM1      0.027922
     66 HAD2       -9.9940   -2.7230   32.0740 hc        1 HM1      0.027922
     67 HHA        -9.2110   -0.5990   31.9110 ha        1 HM1      0.177460
     68 HHB        -9.1100    4.9910   29.2890 ha        1 HM1      0.161732
     69 HHC        -6.0440    2.5560   24.5450 ha        1 HM1      0.173610
     70 HHD        -7.5700   -3.1190   26.4230 ha        1 HM1      0.078646
     71 HAB        -6.3000    4.6440   23.9010 ha        1 HM1      0.099646
     72 HAC        -5.1880   -2.3860   23.2520 ha        1 HM1      0.126660
@<TRIPOS>BOND
     1    1    5 1
     2    1   32 1
     3    1   67 1
     4    2    8 1
     5    2   15 1
     6    2   68 1
     7    3   18 1
     8    3   22 1
     9    3   69 1
    10    4   25 1
    11    4   29 1
    12    4   70 1
    13    5    6 1
    14    5   39 1
    15    6    7 1
    16    6   10 1
    17    7    8 1
    18    7    9 1
    19    8   39 1
    20    9   43 1
    21    9   44 1
    22    9   45 1
    23   10   11 1
    24   10   61 1
    25   10   62 1
    26   11   12 1
    27   11   59 1
    28   11   60 1
    29   12   13 1
    30   12   14 1
    31   15   16 1
    32   15   40 1
    33   16   17 1
    34   16   19 1
    35   17   18 1
    36   17   20 1
    37   18   40 1
    38   19   46 1
    39   19   47 1
    40   19   48 1
    41   20   21 1
    42   20   71 1
    43   21   55 1
    44   21   56 1
    45   22   23 1
    46   22   41 1
    47   23   24 1
    48   23   26 1
    49   24   25 1
    50   24   27 1
    51   25   41 1
    52   26   49 1
    53   26   50 1
    54   26   51 1
    55   27   28 1
    56   27   72 1
    57   28   57 1
    58   28   58 1
    59   29   30 1
    60   29   42 1
    61   30   31 1
    62   30   33 1
    63   31   32 1
    64   31   34 1
    65   32   42 1
    66   33   52 1
    67   33   53 1
    68   33   54 1
    69   34   35 1
    70   34   65 1
    71   34   66 1
    72   35   36 1
    73   35   63 1
    74   35   64 1
    75   36   37 1
    76   36   38 1
@<TRIPOS>SUBSTRUCTURE
     1 HM1         1 TEMP              0 ****  ****    0 ROOT

EOF

cat << EOF > tleap.in
source leaprc.protein.ff19SB
source leaprc.gaff2
source leaprc.water.tip3p
addAtomTypes {
        { "M1"  "Fe" "sp3" }
        { "Y1"  "S" "sp3" }
        { "Y2"  "N" "sp3" }
        { "Y3"  "N" "sp3" }
        { "Y4"  "N" "sp3" }
        { "Y5"  "N" "sp3" }
}
CM1 = loadmol2 CM1.mol2
HM1 = loadmol2 HM1.mol2
FE1 = loadmol2 FE1.mol2
FMN = loadmol2 FMN-ox-H.mol2
LIG = loadmol2 $ligand.mol2 
loadamberparams $ligand.frcmod
loadamberparams HEM.frcmod
loadamberparams frcmod.ions1lm_126_tip3p
loadamberparams 4ZF6_mcpbpy.frcmod
loadamberparams FMN-ox-H.frcmod
mol = loadpdb protein.pdb
bond mol.381.SG mol.613.FE
bond mol.612.NA mol.613.FE
bond mol.612.NB mol.613.FE
bond mol.612.NC mol.613.FE
bond mol.612.ND mol.613.FE
bond mol.380.C mol.381.N
bond mol.381.C mol.382.N
savepdb mol protein_dry.pdb
saveamberparm mol protein_dry.prmtop protein_dry.inpcrd
charge mol
solvatebox mol TIP3PBOX 10.0
addions mol K+ 0
addions mol Cl- 0
charge mol
check mol
savepdb mol protein_solv.pdb
saveamberparm mol protein_solv.prmtop protein_solv.inpcrd
quit
EOF
}

MD_files() {
cat << EOF > em.mdp
; LINES STARTING WITH ';' ARE COMMENTS                                                               
; minim.mdp - used as input into grompp to generate em.tpr                                           
title		    = Minimization	; Title of run                                                         
                                                                                                     
; Parameters describing what to do, when to stop and what to save                                    
integrator	    = steep		; Algorithm (steep = steepest descent minimization)                    
emtol		    = 1000.0  	; Stop minimization when the maximum force < 10.0 kJ/mol                   
emstep          = 0.01      ; Energy step size                                                       
nsteps		    = 50000	  	; Maximum number of (minimization) steps to perform                    
                                                                                                     
; Parameters describing how to find the neighbors of each atom and how to calculate the interactions 
nstlist		    = 1		        ; Frequency to update the neighbor list and long range forces      
cutoff-scheme   = Verlet                                                                             
ns_type		    = grid		    ; Method to determine neighbor list (simple, grid)                 
rlist		    = 1.2		    ; Cut-off for making neighbor list (short range forces)                
coulombtype	    = PME		    ; Treatment of long range electrostatic interactions               
rcoulomb	    = 1.2		    ; long range electrostatic cut-off                                     
vdwtype         = cutoff                                                                             
vdw-modifier    = force-switch                                                                       
rvdw-switch     = 1.0                                                                                
rvdw		    = 1.2		    ; long range Van der Waals cut-off                                     
pbc             = xyz 		    ; Periodic Boundary Conditions                                     
DispCorr        = no                                                                                 

EOF

cat << EOF > nvt.mdp
title                   = Protein-ligand complex NVT equilibration                                                                    
; Run parameters                                                                                          
integrator              = md        ; leap-frog integrator                                                
nsteps                  = 50000     ; 2 * 50000 = 100 ps                                                  
dt                      = 0.002     ; 2 fs                                                                
; Output control                                                                                          
nstenergy               = 500   ; save energies every 1.0 ps                                              
nstlog                  = 500   ; update log file every 1.0 ps                                            
nstxout-compressed      = 500   ; save coordinates every 1.0 ps                                           
; Bond parameters                                                                                         
continuation            = no        ; first dynamics run                                                  
constraint_algorithm    = lincs     ; holonomic constraints                                               
constraints             = h-bonds   ; bonds to H are constrained                                          
lincs_iter              = 1         ; accuracy of LINCS                                                   
lincs_order             = 4         ; also related to accuracy                                            
; Neighbor searching and vdW                                                                              
cutoff-scheme           = Verlet                                                                          
ns_type                 = grid      ; search neighboring grid cells                                       
nstlist                 = 20        ; largely irrelevant with Verlet                                      
rlist                   = 1.2                                                                             
vdwtype                 = cutoff                                                                          
vdw-modifier            = force-switch                                                                    
rvdw-switch             = 1.0                                                                             
rvdw                    = 1.2       ; short-range van der Waals cutoff (in nm)                            
; Electrostatics                                                                                          
coulombtype             = PME       ; Particle Mesh Ewald for long-range electrostatics                   
rcoulomb                = 1.2       ; short-range electrostatic cutoff (in nm)                            
pme_order               = 4         ; cubic interpolation                                                 
fourierspacing          = 0.16      ; grid spacing for FFT                                                
; Temperature coupling                                                                                    
tcoupl                  = V-rescale                     ; modified Berendsen thermostat                   
tc-grps                 = Protein Non-Protein    ; two coupling groups - more accurate                    
tau_t                   = 0.1   0.1                     ; time constant, in ps                            
ref_t                   = 300   300                     ; reference temperature, one for each group, in K 
; Pressure coupling                                                                                       
pcoupl                  = no        ; no pressure coupling in NVT                                         
; Periodic boundary conditions                                                                            
pbc                     = xyz       ; 3-D PBC                                                             
; Dispersion correction is not used for proteins with the C36 additive FF                                 
DispCorr                = no                                                                              
; Velocity generation                                                                                     
gen_vel                 = yes       ; assign velocities from Maxwell distribution                         
gen_temp                = 300       ; temperature for Maxwell distribution                                
gen_seed                = -1        ; generate a random seed                                              

EOF

cat << EOF > npt.mdp
title                   = Protein-ligand complex NPT equilibration                                                                     
; Run parameters                                                                                          
integrator              = md        ; leap-frog integrator                                                
nsteps                  = 50000     ; 2 * 50000 = 100 ps                                                  
dt                      = 0.002     ; 2 fs                                                                
; Output control                                                                                          
nstvout                 = 500       ; save velocities every 1.0 ps                                        
nstenergy               = 500       ; save energies every 1.0 ps                                          
nstlog                  = 500       ; update log file every 1.0 ps                                        
nstxout-compressed      = 500       ; save coordinates every 1.0 ps                                       
; Bond parameters                                                                                         
continuation            = yes       ; continuing from NVT                                                 
constraint_algorithm    = lincs     ; holonomic constraints                                               
constraints             = h-bonds   ; bonds to H are constrained                                          
lincs_iter              = 1         ; accuracy of LINCS                                                   
lincs_order             = 4         ; also related to accuracy                                            
; Neighbor searching and vdW                                                                              
cutoff-scheme           = Verlet                                                                          
ns_type                 = grid      ; search neighboring grid cells                                       
nstlist                 = 20        ; largely irrelevant with Verlet                                      
rlist                   = 1.2                                                                             
vdwtype                 = cutoff                                                                          
vdw-modifier            = force-switch                                                                    
rvdw-switch             = 1.0                                                                             
rvdw                    = 1.2       ; short-range van der Waals cutoff (in nm)                            
; Electrostatics                                                                                          
coulombtype             = PME       ; Particle Mesh Ewald for long-range electrostatics                   
rcoulomb                = 1.2                                                                             
pme_order               = 4         ; cubic interpolation                                                 
fourierspacing          = 0.16      ; grid spacing for FFT                                                
; Temperature coupling                                                                                    
tcoupl                  = V-rescale                     ; modified Berendsen thermostat                   
tc-grps                 = Protein Non-Protein    ; two coupling groups - more accurate                    
tau_t                   = 0.1   0.1                     ; time constant, in ps                            
ref_t                   = 300   300                     ; reference temperature, one for each group, in K 
; Pressure coupling                                                                                       
pcoupl                  = c-rescale                     ; pressure coupling is on for NPT                 
pcoupltype              = isotropic                     ; uniform scaling of box vectors                  
tau_p                   = 2.0                           ; time constant, in ps                            
ref_p                   = 1.0                           ; reference pressure, in bar                      
compressibility         = 4.5e-5                        ; isothermal compressibility of water, bar^-1     
refcoord_scaling        = com                                                                             
; Periodic boundary conditions                                                                            
pbc                     = xyz       ; 3-D PBC                                                             
; Dispersion correction is not used for proteins with the C36 additive FF                                 
DispCorr                = no                                                                              
; Velocity generation                                                                                     
gen_vel                 = no        ; velocity generation off after NVT                                   

EOF

cat << EOF > md.mdp
title                   = Protein-ligand complex MD simulation                                            
; Run parameters                                                                                          
integrator              = md        ; leap-frog integrator                                                
nsteps                  = 5000000   ; 2 * 5000000 = 10000 ps (10 ns)                                      
dt                      = 0.002     ; 2 fs                                                                
; Output control                                                                                          
nstenergy               = 5000      ; save energies every 10.0 ps                                         
nstlog                  = 5000      ; update log file every 10.0 ps                                       
nstxout-compressed      = 5000      ; save coordinates every 10.0 ps                                      
; Bond parameters                                                                                         
continuation            = yes       ; continuing from NPT                                                 
constraint_algorithm    = lincs     ; holonomic constraints                                               
constraints             = h-bonds   ; bonds to H are constrained                                          
lincs_iter              = 1         ; accuracy of LINCS                                                   
lincs_order             = 4         ; also related to accuracy                                            
; Neighbor searching and vdW                                                                              
cutoff-scheme           = Verlet                                                                          
ns_type                 = grid      ; search neighboring grid cells                                       
nstlist                 = 20        ; largely irrelevant with Verlet                                      
rlist                   = 1.2                                                                             
vdwtype                 = cutoff                                                                          
vdw-modifier            = force-switch                                                                    
rvdw-switch             = 1.0                                                                             
rvdw                    = 1.2       ; short-range van der Waals cutoff (in nm)                            
; Electrostatics                                                                                          
coulombtype             = PME       ; Particle Mesh Ewald for long-range electrostatics                   
rcoulomb                = 1.2                                                                             
pme_order               = 4         ; cubic interpolation                                                 
fourierspacing          = 0.16      ; grid spacing for FFT                                                
; Temperature coupling                                                                                    
tcoupl                  = V-rescale                     ; modified Berendsen thermostat                   
tc-grps                 = Protein Non-Protein           ; two coupling groups - more accurate             
tau_t                   = 0.1   0.1                     ; time constant, in ps                            
ref_t                   = 300   300                     ; reference temperature, one for each group, in K 
; Pressure coupling                                                                                       
pcoupl                  = c-rescale             ; pressure coupling is on for NPT                 
pcoupltype              = isotropic                     ; uniform scaling of box vectors                  
tau_p                   = 2.0                           ; time constant, in ps                            
ref_p                   = 1.0                           ; reference pressure, in bar                      
compressibility         = 4.5e-5                        ; isothermal compressibility of water, bar^-1     
; Periodic boundary conditions                                                                            
pbc                     = xyz       ; 3-D PBC                                                             
; Dispersion correction is not used for proteins with the C36 additive FF                                 
DispCorr                = no                                                                              
; Velocity generation                                                                                     
gen_vel                 = no        ; continuing from NPT equilibration                                   

EOF

cat << EOF > ie.mdp
title                   = Protein-ligand complex MD simulation                                            
; Run parameters                                                                                          
integrator              = md        ; leap-frog integrator                                                
nsteps                  = 5000000   ; 2 * 5000000 = 10000 ps (10 ns)                                      
dt                      = 0.002     ; 2 fs                                                                
; Output control                                                                                          
nstenergy               = 1	        ; save energies every 10.0 ps                                         
nstlog                  = 5000      ; update log file every 10.0 ps                                       
nstxout-compressed      = 5000      ; save coordinates every 10.0 ps                                      
; Bond parameters                                                                                         
continuation            = yes       ; continuing from NPT                                                 
constraint_algorithm    = lincs     ; holonomic constraints                                               
constraints             = h-bonds   ; bonds to H are constrained                                          
lincs_iter              = 1         ; accuracy of LINCS                                                   
lincs_order             = 4         ; also related to accuracy                                            
; Neighbor searching and vdW                                                                              
cutoff-scheme           = Verlet                                                                          
ns_type                 = grid      ; search neighboring grid cells                                       
nstlist                 = 20        ; largely irrelevant with Verlet                                      
rlist                   = 1.2                                                                             
vdwtype                 = cutoff                                                                          
vdw-modifier            = force-switch                                                                    
rvdw-switch             = 1.0                                                                             
rvdw                    = 1.2       ; short-range van der Waals cutoff (in nm)                            
; Electrostatics                                                                                          
coulombtype             = PME       ; Particle Mesh Ewald for long-range electrostatics                   
rcoulomb                = 1.2                                                                             
pme_order               = 4         ; cubic interpolation                                                 
fourierspacing          = 0.16      ; grid spacing for FFT                                                
; Temperature coupling                                                                                    
tcoupl                  = V-rescale                     ; modified Berendsen thermostat                   
tc-grps                 = Protein Non-Protein           ; two coupling groups - more accurate             
tau_t                   = 0.1   0.1                     ; time constant, in ps                            
ref_t                   = 300   300                     ; reference temperature, one for each group, in K 
; Pressure coupling                                                                                       
pcoupl                  = c-rescale             ; pressure coupling is on for NPT                 
pcoupltype              = isotropic                     ; uniform scaling of box vectors                  
tau_p                   = 2.0                           ; time constant, in ps                            
ref_p                   = 1.0                           ; reference pressure, in bar                      
compressibility         = 4.5e-5                        ; isothermal compressibility of water, bar^-1     
; Periodic boundary conditions                                                                            
pbc                     = xyz       ; 3-D PBC                                                             
; Dispersion correction is not used for proteins with the C36 additive FF                                 
DispCorr                = no                                                                              
; Velocity generation                                                                                     
gen_vel                 = no        ; continuing from NPT equilibration                                   

EOF

}

#2 position parameter 1 script name 2 job name is required
slurm_sript() {
cat << EOF > $1.sh
#!/bin/bash -l
#SBATCH --job-name=$2   ##job name
#SBATCH -A nsm     ##account name
#SBATCH --nodes=1  ## number of nodes
#SBATCH --nodelist=node1
#SBATCH --error=job.%J.err    ## any error during job submission or execution
#SBATCH --output=job.%J.out   ##any output after job execution 
#SBATCH --partition=GPU_NODES    ##partition name
#SBATCH --gres=gpu:1     ## number of gpu card requires

module load gromacs-gpu/2022.4
source /home/software/ambermpi4py/amber22/amber.sh


EOF

}
