#!/bin/bash
info() {
echo ""
echo ""
echo ""
echo ""
echo "#   #####     #     #    ######     #     #       #       ######     #######         #               ###                                   "
echo "#  #     #     #   #     #     #    #  #  #      # #      #     #    #              ##              #   #                                  "
echo "#  #            # #      #     #    #  #  #     #   #     #     #    #             # #             #     #                                 "
echo "#  #             #       ######     #  #  #    #     #    ######     #####           #             #     #                                 "
echo "#  #             #       #          #  #  #    #######    #   #      #               #      ###    #     #                                 "
echo "#  #     #       #       #          #  #  #    #     #    #    #     #               #      ###     #   #                                  "
echo "#   #####        #       #           ## ##     #     #    #     #    #######       #####    ###      ###                                   "
echo "#                                                                                                                                          "
echo "#  																										                                 "
echo "#  																										                                 "
echo "#  WELCOME to GROMACS CYPWare web interface to calculate Marcus ET parameters for Cytochrome P450 BM3 reactions.                           "      
echo "#  The methodology underlying the CYPWare is developed PULKIT ASATI (JRF NSM GAP-147) under the supervision the PI:                        "
echo "#  Dr. Vaibhav A. Dixit, Asst. Prof., Dept. of Med. Chem.,                                                                                 "
echo "#  NIPER Guwahati                                                                                                                          "
echo "#  NIPER Guwahati in the Advanced Center of Computer-Aided Drug Design (A-CADD). The web interface (GUI) is                                "      
echo "#  developed in collaboration with C-DAC (Mr. Saurabh G. , Mr. Nikhil R. , Dr. Rajendra J.)                                                "      
echo "#  CYPWare software, GUI, websites, tools, layouts, and logos are subject to copyright protection and are the                              "      
echo "#  exclusive property of the Department of Medicinal Chemistry, NIPER Guwahati. The name and logos of the                                  "      
echo "#  NIPER Guwahati website must not be associated with publicity or business promotion without                                              "      
echo "#  NIPER G's prior written approval.                                                                                                       "      
echo "#  																												                         "        
echo "#  GROMACS CYPWare 1.0 is available under the creative commons license and is free for academic research                                   "      
echo "#  groups working in a degree-granting university/institute.                                                                               "      
echo "#  Any work/report/thesis/research-article/review-article resulting from the use of CYPWare 1.0 should properly                            "      
echo "#  cite the software and publication associated with the same.                                                                             "
echo "#                                                                                                                                          "
echo " ######     #######    ######     #######    #     #    ######     #######    #     #     #####     ###    #######     #####    "
echo " #     #    #          #     #    #          ##    #    #     #    #          ##    #    #     #     #     #          #     #   "
echo " #     #    #          #     #    #          # #   #    #     #    #          # #   #    #           #     #          #         "
echo " #     #    #####      ######     #####      #  #  #    #     #    #####      #  #  #    #           #     #####       #####    "
echo " #     #    #          #          #          #   # #    #     #    #          #   # #    #           #     #                #   "
echo " #     #    #          #          #          #    ##    #     #    #          #    ##    #     #     #     #          #     #   "
echo " ######     #######    #          #######    #     #    ######     #######    #     #     #####     ###    #######     #####    "
echo "                                                                                                                                "
echo "#                                                                                                                                    "
echo "#  			                                                                                                                             "
echo "#  GROMACS CYPWare 1.0 makes use of the following opensource tools, thus these need to be installed first from                             "             
echo "#  GitHub, Sourceforge, or as a conda package.                                                                                             "       
echo "#  Ensure that dependencies are satisfied before running CYPWare 1.0, else the calculation will not                                        "       
echo "#  complete as expected.                                                                                                                   "       
echo "#  																												                         "         
echo "#  1) Openbabel 3.1 or higher                                                                                                              "       
echo "#  																												                         "         
echo "#  Openbabel is available as a conda package and can be installed with one of the following commands.                                      "       
echo "#  																												                         "         
echo "#  conda install -c conda-forge openbabel                                                                                                  "       
echo "#  conda install -c conda-forge/label/cf202003 openbabel                                                                                   "       
echo "#  																												                         "         
echo "#  If you don't have conda, then install it from the main website https://www.anaconda.com/                                                "       
echo "#  Instructions for conda installation can be found on its website.                                                                        "       
echo "#  																												                         "         
echo "#  2) AmberTools                                                                                                                           "       
echo "#  																												                         "         
echo "#  																												                         "         
echo "#  AmberTools is a freely available software used for the setup and analysis of MD simulations.                                            "       
echo "#  It is available from the http://ambermd.org/ website. It can also be installed as a conda package                                       "       
echo "#  with any one of the following command.                                                                                                  "       
echo "#  conda install -c conda-forge ambertools                                                                                                 "       
echo "#  conda install -c conda-forge/label/cf202003 ambertools                                                                                  "       
echo "#  																												                         "         
echo "#  3) GROMACS is a molecular dynamics package mainly designed for simulations of proteins, lipids, and nucleic acids.                      "       
echo "#  It was originally developed in the Biophysical Chemistry department of University of Groningen,                                         "       
echo "#  and is now maintained by contributors in universities and research centers worldwide.                                                   "       
echo "#  																												                         "         
echo "#  GROMACS is one of the fastest and most popular software packages available, and can run on central                                      "       
echo "#  processing units (CPUs) and graphics processing units (GPUs).[9] It is free, open-source software                                       "       
echo "#  released under the GNU General Public License (GPL),[3] and starting with version 4.6, the GNU Lesser                                   "       
echo "#  General Public License (LGPL). https://gitlab.com/gromacs/gromacs                                                                       "       
echo "#  4) Statistical tool st                                                                                                                  "       
echo "#  A simple statistical tool available on GitHub is used to extract the averages and standard                                              "       
echo "#  deviations in vertical energy gaps.                                                                                                     "       
echo "#  This is available at https://github.com/nferraz/st                                                                                      "       
echo "#  st can be installed using the following commands                                                                                        "       
echo "#  																												                         "         
echo "#  git clone https://github.com/nferraz/st                                                                                                 "       
echo "#  cd perl5                                                                                                                                "       
echo "#  perl Makefile.PL                                                                                                                        "       
echo "#  make                                                                                                                                    "       
echo "#  make test                                                                                                                               "       
echo "#  make install                                                                                                                            "       
echo "#  																												                         "         
echo "#  5) Extracting Marcus ET parameters                                                                                                      "       
echo "#  This can be done by calling additional scripts on the Linux terminal.                                                                   "       
echo "#  bash get-Marcus-ET-parm-LB.sh file (for ligand-bound state)                                                                             "       
echo "#  bash get-Marcus-ET-parm-LF.sh file (for ligand-free state)                                                                              "       
echo "#  																												                         "         
echo "#  For commercial usage of CYPWare 1.0, please contact the PI at                                                                           "
echo "#  vaibhavadixit@gmail.com or vaibhav@niperguwahati.in                                                                                     "
echo "#  ================================================================================================================			             "
}



## welcome part 1
function welcome_part1() {
colors=(31 32 33 34 35 36)
i=0
while read -r line; do
  color=${colors[$((i % ${#colors[@]}))]}
  echo -e "\033[0;${color}m$line\033[0m"
  i=$((i + 1))
done < <(info)
}

part2_intro() {
echo "######     #    ######  #######     #####      #                                                                                                         "
echo "#     #   # #   #     #    #       #     #    ###                                                                                                        "
echo "#     #  #   #  #     #    #             #     #                                                                                                         "
echo "######  #     # ######     #        #####                                                                                                                "
echo "#       ####### #   #      #       #           #                                                                                                         "
echo "#       #     # #    #     #       #          ###                                                                                                        "
echo "#       #     # #     #    #       #######     #                                                                                                         "
echo "                                                                                                                                                         "
echo "######  #######  #####  #######     #####  ### #     # #     # #          #    ####### ### ####### #     #     #####  ####### ####### ######   #####     "
echo "#     # #     # #     #    #       #     #  #  ##   ## #     # #         # #      #     #  #     # ##    #    #     #    #    #       #     # #     #    "
echo "#     # #     # #          #       #        #  # # # # #     # #        #   #     #     #  #     # # #   #    #          #    #       #     # #          "
echo "######  #     #  #####     #        #####   #  #  #  # #     # #       #     #    #     #  #     # #  #  #     #####     #    #####   ######   #####     "
echo "#       #     #       #    #             #  #  #     # #     # #       #######    #     #  #     # #   # #          #    #    #       #             #    "
echo "#       #     # #     #    #       #     #  #  #     # #     # #       #     #    #     #  #     # #    ##    #     #    #    #       #       #     #    "
echo "#       #######  #####     #        #####  ### #     #  #####  ####### #     #    #    ### ####### #     #     #####     #    ####### #        #####     "
echo "                                                                                                                                                         "
echo "####### #     # ###  #####      #####   #####  ######  ### ######  #######    ### #     # #     # ####### #       #     # ####### ######                 "
echo "   #    #     #  #  #     #    #     # #     # #     #  #  #     #    #        #  ##    # #     # #     # #       #     # #       #     #                "
echo "   #    #     #  #  #          #       #       #     #  #  #     #    #        #  # #   # #     # #     # #       #     # #       #     #                "
echo "   #    #######  #   #####      #####  #       ######   #  ######     #        #  #  #  # #     # #     # #       #     # #####   #     #                "
echo "   #    #     #  #        #          # #       #   #    #  #          #        #  #   # #  #   #  #     # #        #   #  #       #     #                "
echo "   #    #     #  #  #     #    #     # #     # #    #   #  #          #        #  #    ##   # #   #     # #         # #   #       #     #                "
echo "   #    #     # ###  #####      #####   #####  #     # ### #          #       ### #     #    #    ####### #######    #    ####### ######                 "
echo "                                                                                                                                                         "
echo "####### #     # ####### ######     #     #####  ####### ### ####### #     #    ####### #######    ####### #     # ####### ######   #####  #     #        "
echo "#        #   #     #    #     #   # #   #     #    #     #  #     # ##    #    #     # #          #       ##    # #       #     # #     #  #   #         "
echo "#         # #      #    #     #  #   #  #          #     #  #     # # #   #    #     # #          #       # #   # #       #     # #         # #          "
echo "#####      #       #    ######  #     # #          #     #  #     # #  #  #    #     # #####      #####   #  #  # #####   ######  #  ####    #           "
echo "#         # #      #    #   #   ####### #          #     #  #     # #   # #    #     # #          #       #   # # #       #   #   #     #    #           "
echo "#        #   #     #    #    #  #     # #     #    #     #  #     # #    ##    #     # #          #       #    ## #       #    #  #     #    #           "
echo "####### #     #    #    #     # #     #  #####     #    ### ####### #     #    ####### #          ####### #     # ####### #     #  #####     #           "
echo "                                                                                                                                                         "
echo "   #    #     # ######     ######  ###  #####  #######    #    #     #  #####  #######    ####### ####### ######                                         "
echo "  # #   ##    # #     #    #     #  #  #     #    #      # #   ##    # #     # #          #       #     # #     #                                        "
echo " #   #  # #   # #     #    #     #  #  #          #     #   #  # #   # #       #          #       #     # #     #                                        "
echo "#     # #  #  # #     #    #     #  #   #####     #    #     # #  #  # #       #####      #####   #     # ######                                         "
echo "####### #   # # #     #    #     #  #        #    #    ####### #   # # #       #          #       #     # #   #                                          "
echo "#     # #    ## #     #    #     #  #  #     #    #    #     # #    ## #     # #          #       #     # #    #                                         "
echo "#     # #     # ######     ######  ###  #####     #    #     # #     #  #####  #######    #       ####### #     #                                        "
echo "                                                                                                                                                         "
echo "####### #       #######  #####  ####### ######  ####### #     #    ####### ######     #    #     #  #####  ####### ####### ######                        "
echo "#       #       #       #     #    #    #     # #     # ##    #       #    #     #   # #   ##    # #     # #       #       #     #                       "
echo "#       #       #       #          #    #     # #     # # #   #       #    #     #  #   #  # #   # #       #       #       #     #                       "
echo "#####   #       #####   #          #    ######  #     # #  #  #       #    ######  #     # #  #  #  #####  #####   #####   ######                        "
echo "#       #       #       #          #    #   #   #     # #   # #       #    #   #   ####### #   # #       # #       #       #   #                         "
echo "#       #       #       #     #    #    #    #  #     # #    ##       #    #    #  #     # #    ## #     # #       #       #    #                        "
echo "####### ####### #######  #####     #    #     # ####### #     #       #    #     # #     # #     #  #####  #       ####### #     #                       "
echo "                                                                                                                                                         "
echo "######     #    ####### #######     #####     #    #        #####  #     # #          #    ####### ### ####### #     #                                   "
echo "#     #   # #      #    #          #     #   # #   #       #     # #     # #         # #      #     #  #     # ##    #                                   "
echo "#     #  #   #     #    #          #        #   #  #       #       #     # #        #   #     #     #  #     # # #   #                                   "
echo "######  #     #    #    #####      #       #     # #       #       #     # #       #     #    #     #  #     # #  #  #                                   "
echo "#   #   #######    #    #          #       ####### #       #       #     # #       #######    #     #  #     # #   # #                                   "
echo "#    #  #     #    #    #          #     # #     # #       #     # #     # #       #     #    #     #  #     # #    ##                                   "
echo "#     # #     #    #    #######     #####  #     # #######  #####   #####  ####### #     #    #    ### ####### #     #                                   "
echo "																																							   "
echo "																																						   "
}

## welcome part 2
function welcome_part2() {
colors=(31 32 33 34 35 36)
i=0
while read -r line; do
  color=${colors[$((i % ${#colors[@]}))]}
  echo -e "\033[0;${color}m$line\033[0m"
  i=$((i + 1))
done < <(part2_intro)
}